# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

import pandas as pd
import yaml

# Import configuration files
params = yaml.load(open("config/params.yml", "r"), Loader=yaml.SafeLoader)
features = yaml.load(open("config/features.yml", "r"), Loader=yaml.SafeLoader)
samples = pd.read_table("config/samples.tsv", comment="#", dtype="str")

# Generate useful variables
SAMPLES = samples["sample_id"].drop_duplicates().values.tolist()
SAMPLE_LIBRARY = samples[["sample_id", "library_id"]].values.tolist()
BAM_REPORTS = ["stats.tsv", "flagstats.txt", "idxstats.tsv"]


include: "rules/folders.smk"
include: "rules/helpers/__main__.smk"
include: "rules/reference/__main__.smk"
include: "rules/reads.smk"
include: "rules/preprocess.smk"
include: "rules/multiqc.smk"
# include: "rules/quantify/__main__.smk"
# include: "rules/report/__main__.smk"


rule all:
    input:
        # rules.reads.input,
        # rules.reference.input,
        rules.preprocess__all.input,
        # rules.quantify.input,
        # rules.report.input,
