# Main entrypoint of the workflow.
# Please follow the best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

import pandas as pd
import yaml

# Import configuration files
params = yaml.load(open("config/params.yml", "r"), Loader=yaml.SafeLoader)
features = yaml.load(open("config/features.yml", "r"), Loader=yaml.SafeLoader)
samples = pd.read_table("config/samples.tsv", comment="#", dtype="str")

# Generate useful variables
SAMPLES = samples["sample"].drop_duplicates().values.tolist()
SAMPLE_LIB = samples[["sample", "library"]].values.tolist()
MAX_THREADS = params["max_threads"]
BAM_REPORTS = ["stats.tsv", "flagstats.txt", "idxstats.tsv"]


include: "rules/folders.smk"
include: "rules/reads_functions.smk"
include: "rules/reads.smk"
include: "rules/reference.smk"
include: "rules/fastp_functions.smk"
include: "rules/fastp.smk"
include: "rules/star_functions.smk"
include: "rules/star.smk"
include: "rules/samtools.smk"
include: "rules/report_library_functions.smk"
include: "rules/report_step.smk"
include: "rules/report_library.smk"


rule all:
    input:
        # rules.reads_link.input,
        # rules.reads_fastqc.input,
        # rules.reference.input,
        # rules.fastp_all.input,
        # rules.ribodetector_all_samples.input,
        # rules.star_index.input,
        # rules.star_all_samples.input,
        rules.star_all.input,  # the crams and compressed files are not in the reports
        rules.report_step.input,
        rules.report_library.input,
