default-resources:
    runtime: 1h
    mem_mb: 1G
    disk_mb: 100G

set-threads:
    preprocess__fastp__trim__: 24

set-resources:
    preprocess__fastp__trim__:
        mem_mb: 4G
        runtime: 1h
