default-resources:
    runtime: 1h
    mem_mb: 1G

set-threads:
    fastp: 24
    star__index: 24
    star__align: 24

set-resources:
    fastp:
        mem_mb: 4G
        runtime: 1h
    star__index:
        mem_mb: 32G
        runtime: 1d
    star__align:
        mem_mb: 32G
        runtime: 1d
