__use_yte__: True

default-resources:
    runtime: 60
    mem_mb: 1024

set-threads:
    fastp: 24
    star__index: 24
    star__align: 24

set-resources:
    fastp:
        mem_mb: 4 * 1024
        runtime: 1h
    star__index:
        mem_mb: 32 * 1024
        runtime: 1d
    star__align:
        mem_mb: 32 * 1024
        runtime: 1d
