default-resources:
    runtime: 1h
    mem_mb: 1G
    disk_mb: 100G

set-threads:
    single_core_rule: 1
    multi_core_rule: 16

set-resources:
    high_memory_rule: 
        mem_mb: 12G
    long_running_rule:
        runtime: 2h
